
### Create new user

POST http://localhost:3000/user/
Content-Type: application/json

{
    "name": "Diego",
    "email": "patricia@gmail.com",
    "password": "Test@1234"
}

### Login User

POST http://localhost:3000/auth
Content-Type: application/json

{
    "email": "diego@gmail.com",
    "password": "Test@1234"
}


### Create a new expense

POST http://localhost:3000/expenses
Content-Type: application/json
Authorization: Bearer 
token

{
    "description": "shein",
    "date": "2023-04-10", 
    "amount": 22
}

### Get all expenses
GET http://localhost:3000/expenses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNhOTE1ODRiLTc0NmEtNGM1NC04M2M2LTg2MDI4MjQwZDM3NSIsImlhdCI6MTY4MTUxMTA2NywiZXhwIjoxNjgxNTExMTI3fQ.Jm6CFHv4Q3ja-eQxkyLx5dZP5KXKj4lRIOmvNq1rkG8

###

GET http://localhost:3000/expenses/5a03de46-bcd2-4346-9397-2ec925574483
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNhOTE1ODRiLTc0NmEtNGM1NC04M2M2LTg2MDI4MjQwZDM3NSIsImlhdCI6MTY4MTUxMDk3OSwiZXhwIjoxNjgxNTExMDM5fQ.LBfgf8fJ2qKrbp5BfH6AQuX0FW4qPIQbHezimYkdUzs


###

PATCH  http://localhost:3000/expenses/68ddd7dc-6ac9-4a82-81db-6fcebcf70261
Content-Type: application/json

{
    "amount": 100
}



###

DELETE  http://localhost:3000/expenses/f1f08115-9134-4246-9e82-232fe4ddc353
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNhOTE1ODRiLTc0NmEtNGM1NC04M2M2LTg2MDI4MjQwZDM3NSIsImlhdCI6MTY4MTUxMDk3OSwiZXhwIjoxNjgxNTExMDM5fQ.LBfgf8fJ2qKrbp5BfH6AQuX0FW4qPIQbHezimYkdUzs