### Create new user

POST http://localhost:3000/user/
Content-Type: application/json

{
    "name": "Patricia",
    "email": "patricia@gmail.com",
    "password": "Test@1234"
}

### Login User

POST http://localhost:3000/auth
Content-Type: application/json

{
    "email": "patricia@gmail.com",
    "password": "Test@1234"
}


### Create a new expense

POST http://localhost:3000/expenses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzNGQzNmU2LTgyYWEtNGU5Ny1iYWY4LTNlMDg0OGFlZDhjNyIsImlhdCI6MTY4MTQ5Mzk4OCwiZXhwIjoxNjgxNDk0MDQ4fQ.4OEDpDJQFEoLIrn-sXWCyh5OYMrRfdBGw5BuVqsJXG0

{
    "description": "shein",
    "date": "2023-04-10", 
    "amount": 22
}

### Get all expenses
GET http://localhost:3000/expenses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzNGQzNmU2LTgyYWEtNGU5Ny1iYWY4LTNlMDg0OGFlZDhjNyIsImlhdCI6MTY4MTQ5Mzk4OCwiZXhwIjoxNjgxNDk0MDQ4fQ.4OEDpDJQFEoLIrn-sXWCyh5OYMrRfdBGw5BuVqsJXG0

###

GET http://localhost:3000/expenses/4d1aca0c-2ecd-4519-8bd0-f35518da799f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFiNmMzZDNlLWJlYmQtNDRkOC05OGNmLWM2YWU4ZTRjZjZiZSIsImlhdCI6MTY4MTQ4MjYzMCwiZXhwIjoxNjgxNDgyNjkwfQ.gz6I_AIqeTrxlubcPMOOQB6X_4lLuMJWR0NWdm5Is3s


###

PATCH  http://localhost:3000/expenses/68ddd7dc-6ac9-4a82-81db-6fcebcf70261
Content-Type: application/json

{
    "amount": 100
}



###

DELETE  http://localhost:3000/expenses/dcd4e123-78eb-4af3-8c4a-99e5e0451736


